POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=AIzaSyCa3SJjIk0IPA_wfVVMbtQ7YrBUndNrvPQ HTTP/1.1
content-type: application/json

{"contents":[{"parts":[{"text":"Explain how AI works"}]}]}